/*Consultas Personalizadas*/

db.Frutas.find()


db.Frutas.find( { $and: [ { Numempresas: { $gte:15 } }, {"Familia.Frutadulce":{$eq: true }},{FechaRecogida:{$eq:new Date ("2020-07-19")}} ] } ) // En esta búsqueda he pedido las frutas  que sean Dulces , que tengan mas de 15 empresas recogiéndolas y su fecha de recolección sea el 19 de julio .

/* { "_id" : ObjectId("5fbbebb3e93269a7a944b436"), "Fruta" : "Melocoton", "Numempresas" : 17, "Recogida" : { "lugaresrecogidas" : [ "Sundsvalls", "Bolinas" ], "pais" : "Suecia" }, "FechaRecogida" : ISODate("2020-07-19T00:00:00Z"), "Familia" : { "Frutadulce" : true, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }  */

db.Frutas.find({$or: [{"Familia.Exoticas":{$ne:false}},{Numempresas:{$not:{$lte:16}}},{FechaRecogida:{$lte:new Date ("2020-05-05")}} ]}) // En esta búsqueda he usado el operador $or para buscar las frutas que cumpla cualquiera de mis especificaciones,buscaba las frutas que no fueran exóticas,que haya un total de más de 16 empresas recolectandolas o que su fecha de recolección sea antes del 5 de mayo.

/* { "_id" : ObjectId("5fbbebb3e93269a7a944b433"), "Fruta" : "Manzana", "Numempresas" : 15, "Recogida" : { "lugaresrecogidas" : [ "Sevilla", "Murcia" ], "pais" : "España" }, "FechaRecogida" : ISODate("2020-04-20T00:00:00Z"), "Familia" : { "Frutadulce" : true, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b434"), "Fruta" : "Platano", "Numempresas" : 25, "Recogida" : { "lugaresrecogidas" : [ "Rennes", "Nantes" ], "pais" : "Francia" }, "FechaRecogida" : ISODate("2020-02-13T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b435"), "Fruta" : "Fresa", "Numempresas" : 23, "Recogida" : { "lugaresrecogidas" : [ "Liverpool", "Sheffield", "Colchester" ], "pais" : "Reino Unido" }, "FechaRecogida" : ISODate("2020-01-16T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : true, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b436"), "Fruta" : "Melocoton", "Numempresas" : 17, "Recogida" : { "lugaresrecogidas" : [ "Sundsvalls", "Bolinas" ], "pais" : "Suecia" }, "FechaRecogida" : ISODate("2020-07-19T00:00:00Z"), "Familia" : { "Frutadulce" : true, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b438"), "Fruta" : "Sandia", "Numempresas" : 30, "Recogida" : { "lugaresrecogidas" : [ "Lahti", "Turku" ], "pais" : "Finlandia" }, "FechaRecogida" : ISODate("2020-05-13T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : true, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43b"), "Fruta" : "Kiwi", "Numempresas" : 40, "Recogida" : { "lugaresrecogidas" : [ "Essen", "Hannover" ], "pais" : "Alemania" }, "FechaRecogida" : ISODate("2020-03-15T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43c"), "Fruta" : "Mandarina", "Numempresas" : 78, "Recogida" : { "lugaresrecogidas" : [ "Zagreb", "Knin" ], "pais" : "Croacia" }, "FechaRecogida" : ISODate("2020-03-10T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : true } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43d"), "Fruta" : "Arandano", "Numempresas" : 5, "Recogida" : { "lugaresrecogidas" : [ "Essen", "Hannover" ], "pais" : "Alemania" }, "FechaRecogida" : ISODate("2020-04-10T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } } */

db.Frutas.find({$nor:[{"Recogida.lugaresrecogidas": { $all: [ "Rennes","Nantes"] } },{"Recogida.pais":/España/},{FechaRecogida:{$gt:new Date ("2020-11-10")}} ]} )//En esta consulta he consultado las frutas que no hayan sido recogidas en Rennes y en Nantes y que no hayan sido recogidas en una fecha posterior a el 11 de noviembre del 2020

/*{ "_id" : ObjectId("5fbbebb3e93269a7a944b435"), "Fruta" : "Fresa", "Numempresas" : 23, "Recogida" : { "lugaresrecogidas" : [ "Liverpool", "Sheffield", "Colchester" ], "pais" : "Reino Unido" }, "FechaRecogida" : ISODate("2020-01-16T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : true, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b436"), "Fruta" : "Melocoton", "Numempresas" : 17, "Recogida" : { "lugaresrecogidas" : [ "Sundsvalls", "Bolinas" ], "pais" : "Suecia" }, "FechaRecogida" : ISODate("2020-07-19T00:00:00Z"), "Familia" : { "Frutadulce" : true, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b437"), "Fruta" : "Melon", "Numempresas" : 9, "Recogida" : { "lugaresrecogidas" : [ "Graz", "Salzburgo" ], "pais" : "Austria" }, "FechaRecogida" : ISODate("2020-08-08T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : true, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b438"), "Fruta" : "Sandia", "Numempresas" : 30, "Recogida" : { "lugaresrecogidas" : [ "Lahti", "Turku" ], "pais" : "Finlandia" }, "FechaRecogida" : ISODate("2020-05-13T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : true, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43b"), "Fruta" : "Kiwi", "Numempresas" : 40, "Recogida" : { "lugaresrecogidas" : [ "Essen", "Hannover" ], "pais" : "Alemania" }, "FechaRecogida" : ISODate("2020-03-15T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43c"), "Fruta" : "Mandarina", "Numempresas" : 78, "Recogida" : { "lugaresrecogidas" : [ "Zagreb", "Knin" ], "pais" : "Croacia" }, "FechaRecogida" : ISODate("2020-03-10T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : true } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43d"), "Fruta" : "Arandano", "Numempresas" : 5, "Recogida" : { "lugaresrecogidas" : [ "Essen", "Hannover" ], "pais" : "Alemania" }, "FechaRecogida" : ISODate("2020-04-10T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }*/


db.Frutas.find({$or: [{$and:[{Numempresas:{$gte:10}},{FechaRecogida:{$lt:new Date ("2020-11-10")}}]},{"Familia.Frutadulce":{$eq:true}}]});//He buscado las frutas que tengan 10 o más empresas recolectandolas y realicen su recolección en una fecha anterior al 10 de noviembre o sean frutas dulces.

/* { "_id" : ObjectId("5fbbebb3e93269a7a944b433"), "Fruta" : "Manzana", "Numempresas" : 15, "Recogida" : { "lugaresrecogidas" : [ "Sevilla", "Murcia" ], "pais" : "España" }, "FechaRecogida" : ISODate("2020-04-20T00:00:00Z"), "Familia" : { "Frutadulce" : true, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b434"), "Fruta" : "Platano", "Numempresas" : 25, "Recogida" : { "lugaresrecogidas" : [ "Rennes", "Nantes" ], "pais" : "Francia" }, "FechaRecogida" : ISODate("2020-02-13T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b435"), "Fruta" : "Fresa", "Numempresas" : 23, "Recogida" : { "lugaresrecogidas" : [ "Liverpool", "Sheffield", "Colchester" ], "pais" : "Reino Unido" }, "FechaRecogida" : ISODate("2020-01-16T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : true, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b436"), "Fruta" : "Melocoton", "Numempresas" : 17, "Recogida" : { "lugaresrecogidas" : [ "Sundsvalls", "Bolinas" ], "pais" : "Suecia" }, "FechaRecogida" : ISODate("2020-07-19T00:00:00Z"), "Familia" : { "Frutadulce" : true, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b438"), "Fruta" : "Sandia", "Numempresas" : 30, "Recogida" : { "lugaresrecogidas" : [ "Lahti", "Turku" ], "pais" : "Finlandia" }, "FechaRecogida" : ISODate("2020-05-13T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : true, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b439"), "Fruta" : "Limon", "Numempresas" : 15, "Recogida" : { "lugaresrecogidas" : [ "Murcia", "Huelva" ], "pais" : "España" }, "FechaRecogida" : ISODate("2020-10-24T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : true } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43a"), "Fruta" : "Naranja", "Numempresas" : 15, "Recogida" : { "lugaresrecogidas" : [ "Valencia", "Sevilla" ], "pais" : "España" }, "FechaRecogida" : ISODate("2020-11-07T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : true } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43b"), "Fruta" : "Kiwi", "Numempresas" : 40, "Recogida" : { "lugaresrecogidas" : [ "Essen", "Hannover" ], "pais" : "Alemania" }, "FechaRecogida" : ISODate("2020-03-15T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43c"), "Fruta" : "Mandarina", "Numempresas" : 78, "Recogida" : { "lugaresrecogidas" : [ "Zagreb", "Knin" ], "pais" : "Croacia" }, "FechaRecogida" : ISODate("2020-03-10T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : true } } */

db.Frutas.find({$and:[{FechaRecogida:{$lt: new Date("2020-08-01") , $gte: new Date("2020-01-01")}},{"Recogida.pais":{$ne:"Francia"}}]})// He pedido las frutas que se recojan antes del 1 de agosto y las frutas que no hayan sido recogidas en Francia.


/* { "_id" : ObjectId("5fbbebb3e93269a7a944b433"), "Fruta" : "Manzana", "Numempresas" : 15, "Recogida" : { "lugaresrecogidas" : [ "Sevilla", "Murcia" ], "pais" : "España" }, "FechaRecogida" : ISODate("2020-04-20T00:00:00Z"), "Familia" : { "Frutadulce" : true, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b435"), "Fruta" : "Fresa", "Numempresas" : 23, "Recogida" : { "lugaresrecogidas" : [ "Liverpool", "Sheffield", "Colchester" ], "pais" : "Reino Unido" }, "FechaRecogida" : ISODate("2020-01-16T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : true, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b436"), "Fruta" : "Melocoton", "Numempresas" : 17, "Recogida" : { "lugaresrecogidas" : [ "Sundsvalls", "Bolinas" ], "pais" : "Suecia" }, "FechaRecogida" : ISODate("2020-07-19T00:00:00Z"), "Familia" : { "Frutadulce" : true, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b438"), "Fruta" : "Sandia", "Numempresas" : 30, "Recogida" : { "lugaresrecogidas" : [ "Lahti", "Turku" ], "pais" : "Finlandia" }, "FechaRecogida" : ISODate("2020-05-13T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : true, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43b"), "Fruta" : "Kiwi", "Numempresas" : 40, "Recogida" : { "lugaresrecogidas" : [ "Essen", "Hannover" ], "pais" : "Alemania" }, "FechaRecogida" : ISODate("2020-03-15T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43c"), "Fruta" : "Mandarina", "Numempresas" : 78, "Recogida" : { "lugaresrecogidas" : [ "Zagreb", "Knin" ], "pais" : "Croacia" }, "FechaRecogida" : ISODate("2020-03-10T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : false, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : true } }
{ "_id" : ObjectId("5fbbebb3e93269a7a944b43d"), "Fruta" : "Arandano", "Numempresas" : 5, "Recogida" : { "lugaresrecogidas" : [ "Essen", "Hannover" ], "pais" : "Alemania" }, "FechaRecogida" : ISODate("2020-04-10T00:00:00Z"), "Familia" : { "Frutadulce" : false, "Exoticas" : true, "Bayas" : false, "Cucurbitaceas" : false, "Citrico" : false } } */






db.EmpresasFrutas.find({$and:[{Numempleados:{$gte:100}},{"Funcion.frutas":{$ne:["Arandano","Kiwi"]}},{beneficios:{$elemMatch:{$gt:100000,$lt:500000}}}]})//En esta consulta he pedido las empresas con 100 o más empleados, las empresas que no se especialicen en arando o Kiwi y que tengan unos  beneficios en el primer semestre superior a 100000 y el segundo semestre inferiores a 500000

/*{ "_id" : ObjectId("5fbbfdc6e93269a7a944b43e"), "Nombreempresa" : "Frotogida", "Numempleados" : 180, "Funcion" : { "frutas" : [ "Manzana", "Limon" ], "paisrecogida" : [ "España" ] }, "beneficios" : [ 42000000, 120000 ], "FechaDisponibilidadEnvios" : ISODate("2020-06-15T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b43f"), "Nombreempresa" : "Recofrutes", "Numempleados" : 200, "Funcion" : { "frutas" : [ "Platano" ], "paisrecogida" : [ "Francia" ] }, "beneficios" : [ 500000, 170000 ], "FechaDisponibilidadEnvios" : ISODate("2020-04-20T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b440"), "Nombreempresa" : "Vieta company", "Numempleados" : 120, "Funcion" : { "frutas" : [ "Platano", "Melon" ], "paisrecogida" : [ "Francia", "Austria" ] }, "beneficios" : [ 260000, 80000 ], "FechaDisponibilidadEnvios" : ISODate("2020-03-28T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b445"), "Nombreempresa" : "Recogidas Jimenez", "Numempleados" : 200, "Funcion" : { "frutas" : [ "Melon" ], "paisrecogida" : [ "Austria" ] }, "beneficios" : [ 570000, 160000 ], "FechaDisponibilidadEnvios" : ISODate("2020-12-28T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b446"), "Nombreempresa" : "Paleyu Frutis", "Numempleados" : 150, "Funcion" : { "frutas" : [ "Kiwi" ], "paisrecogida" : [ "Alemania" ] }, "beneficios" : [ 180785, 189036 ], "FechaDisponibilidadEnvios" : ISODate("2020-05-02T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b448"), "Nombreempresa" : "Recarte", "Numempleados" : 140, "Funcion" : { "frutas" : [ "Mandarina", "Arandano" ], "paisrecogida" : [ "Finlandia", "Francia" ] }, "beneficios" : [ 360785, 120000 ], "FechaDisponibilidadEnvios" : ISODate("2020-05-10T00:00:00Z") } */



db.EmpresasFrutas.find({$nor:[{"Funcion.frutas":{$eq:["Platano","Melon"]}},{"Funcion.paisRecogida":{$eq:["España"]}}]}) //En esta consulta he pedido las empresas que no trabajen con plátanos y melón , no  recojan las frutas solo  en España


/* { "_id" : ObjectId("5fbac262f603fe95e25bb865"), "Nombreempresa" : "Recofrutes", "Numempleados" : 200, "Funcion" : { "frutas" : [ "Platano" ], "paisRecogida" : [ "Francia" ], "FechaDisponibilidadEnvios" : ISODate("2020-04-20T00:00:00Z") } }
{ "_id" : ObjectId("5fbac262f603fe95e25bb867"), "Nombreempresa" : "RC Company", "Numempleados" : 100, "Funcion" : { "frutas" : [ "Fresa", "Melocoton" ], "paisRecogida" : [ "Reino Unido", "Suecia" ], "FechaDisponibilidadEnvios" : ISODate("2020-09-17T00:00:00Z") } }
{ "_id" : ObjectId("5fbac262f603fe95e25bb868"), "Nombreempresa" : "RF Melon", "Numempleados" : 70, "Funcion" : { "frutas" : [ "Sandia", "Limon" ], "paisRecogida" : [ "España", "Finlandia" ], "FechaDisponibilidadEnvios" : ISODate("2020-10-06T00:00:00Z") } }
{ "_id" : ObjectId("5fbac262f603fe95e25bb869"), "Nombreempresa" : "WIN company", "Numempleados" : 40, "Funcion" : { "frutas" : [ "Naranja", "Fresa", "Platano" ], "paisRecogida" : [ "España", "Reino Unido" ], "FechaDisponibilidadEnvios" : ISODate("2020-08-01T00:00:00Z") } }
{ "_id" : ObjectId("5fbac262f603fe95e25bb86a"), "Nombreempresa" : "Frutas Paco", "Numempleados" : 50, "Funcion" : { "frutas" : [ "Manzana", "Limon", "Sandia", "Melocoton" ], "paisRecogida" : [ "España", "Suecia", "Finlandia" ], "FechaDisponibilidadEnvios" : ISODate("2020-12-17T00:00:00Z") } }
{ "_id" : ObjectId("5fbac262f603fe95e25bb86b"), "Nombreempresa" : "Recogidas Jimenez", "Numempleados" : 200, "Funcion" : { "frutas" : [ "Melon" ], "paisRecogida" : [ "Austria" ], "FechaDisponibilidadEnvios" : ISODate("2020-12-28T00:00:00Z") } }
{ "_id" : ObjectId("5fbac262f603fe95e25bb86c"), "Nombreempresa" : "Paleyu Frutis", "Numempleados" : 150, "Funcion" : { "frutas" : [ "Kiwi" ], "paisRecogida" : [ "Alemania" ], "FechaDisponibilidadEnvios" : ISODate("2020-05-02T00:00:00Z") } }
{ "_id" : ObjectId("5fbac262f603fe95e25bb86d"), "Nombreempresa" : "Recogidas Jimenez", "Numempleados" : 200, "Funcion" : { "frutas" : [ "Arandano", "Kiwi" ], "paisRecogida" : [ "Croatia" ], "FechaDisponibilidadEnvios" : ISODate("2020-06-28T00:00:00Z") } }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b43e"), "Nombreempresa" : "Frotogida", "Numempleados" : 180, "Funcion" : { "frutas" : [ "Manzana", "Limon" ], "paisrecogida" : [ "España" ] }, "beneficios" : [ 42000000, 120000 ], "FechaDisponibilidadEnvios" : ISODate("2020-06-15T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b43f"), "Nombreempresa" : "Recofrutes", "Numempleados" : 200, "Funcion" : { "frutas" : [ "Platano" ], "paisrecogida" : [ "Francia" ] }, "beneficios" : [ 500000, 170000 ], "FechaDisponibilidadEnvios" : ISODate("2020-04-20T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b441"), "Nombreempresa" : "RC Company", "Numempleados" : 100, "Funcion" : { "frutas" : [ "Fresa", "Melocoton" ], "paisrecogida" : [ "Reino Unido", "Suecia" ] }, "beneficios" : [ 100000, 30000 ], "FechaDisponibilidadEnvios" : ISODate("2020-09-17T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b442"), "Nombreempresa" : "RF Melon", "Numempleados" : 70, "Funcion" : { "frutas" : [ "Sandia", "Limon" ], "paisrecogida" : [ "España", "Finlandia" ] }, "beneficios" : [ 80000, 30000 ], "FechaDisponibilidadEnvios" : ISODate("2020-10-06T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b443"), "Nombreempresa" : "WIN company", "Numempleados" : 40, "Funcion" : { "frutas" : [ "Naranja", "Fresa", "Platano" ], "paisrecogida" : [ "España", "Reino Unido" ] }, "beneficios" : [ 90000, 40000 ], "FechaDisponibilidadEnvios" : ISODate("2020-08-01T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b444"), "Nombreempresa" : "Frutas Paco", "Numempleados" : 50, "Funcion" : { "frutas" : [ "Manzana", "Limon", "Sandia", "Melocoton" ], "paisRecogida" : [ "España", "Suecia", "Finlandia" ] }, "beneficios" : [ 69250, 23546 ], "FechaDisponibilidadEnvios" : ISODate("2020-12-17T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b445"), "Nombreempresa" : "Recogidas Jimenez", "Numempleados" : 200, "Funcion" : { "frutas" : [ "Melon" ], "paisrecogida" : [ "Austria" ] }, "beneficios" : [ 570000, 160000 ], "FechaDisponibilidadEnvios" : ISODate("2020-12-28T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b446"), "Nombreempresa" : "Paleyu Frutis", "Numempleados" : 150, "Funcion" : { "frutas" : [ "Kiwi" ], "paisrecogida" : [ "Alemania" ] }, "beneficios" : [ 180785, 189036 ], "FechaDisponibilidadEnvios" : ISODate("2020-05-02T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b447"), "Nombreempresa" : "Recogidas Jimenez", "Numempleados" : 200, "Funcion" : { "frutas" : [ "Arandano", "Kiwi" ], "paisrecogida" : [ "Croatia" ] }, "beneficios" : [ 600785, 371000 ], "FechaDisponibilidadEnvios" : ISODate("2020-06-28T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b448"), "Nombreempresa" : "Recarte", "Numempleados" : 140, "Funcion" : { "frutas" : [ "Mandarina", "Arandano" ], "paisrecogida" : [ "Finlandia", "Francia" ] }, "beneficios" : [ 360785, 120000 ], "FechaDisponibilidadEnvios" : ISODate("2020-05-10T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b449"), "Nombreempresa" : "Recoltino", "Numempleados" : 100, "Funcion" : { "frutas" : [ "Arandano", "Kiwi" ], "paisrecogida" : [ "Croatia", "Reino Unido" ] }, "beneficios" : [ 780785, 150000 ], "FechaDisponibilidadEnvios" : ISODate("2020-06-10T00:00:00Z") } */

db.EmpresasFrutas.find({$and:[{"Funcion.frutas":{$all:["Limon", "Sandia"]}},{beneficios:{$elemMatch:{$lt:90000,$gt:20000}}}]})// He pedido, las empresas que se encarguen de los limones o sandia y tengan unos beneficios semestrales menores a 90000 y en el segundo semestre superior a 20000 
/* { "_id" : ObjectId("5fbbfdc6e93269a7a944b442"), "Nombreempresa" : "RF Melon", "Numempleados" : 70, "Funcion" : { "frutas" : [ "Sandia", "Limon" ], "paisrecogida" : [ "España", "Finlandia" ] }, "beneficios" : [ 80000, 30000 ], "FechaDisponibilidadEnvios" : ISODate("2020-10-06T00:00:00Z") }
{ "_id" : ObjectId("5fbbfdc6e93269a7a944b444"), "Nombreempresa" : "Frutas Paco", "Numempleados" : 50, "Funcion" : { "frutas" : [ "Manzana", "Limon", "Sandia", "Melocoton" ], "paisRecogida" : [ "España", "Suecia", "Finlandia" ] }, "beneficios" : [ 69250, 23546 ], "FechaDisponibilidadEnvios" : ISODate("2020-12-17T00:00:00Z") } */

